Feat: biyooon by using zenohex instead of Node.connect
biyooon-ex/giocci pull request #26
Opened 2024-12-12 07:14 UTC by fomfom

ClientとRelayの間と、RelayとEngineの間をNode.connectを用いて接続していた部分をZenohexに置き換えたものになります。

2024-12-12 13:08 UTC, takasehideki commented on lib/giocci/hello.ex
> +end
これはテストコードではないですか？？
このリポジトリには入れないほうがいいと思います．テストコード用には新しいmixプロジェクト（例えば `giocci_feat_test` ）を作って，そこの mix.exs に `defp [{:giocci, ~~}]` したものを用意したほうがいいでしょう．

2024-12-16 05:29 UTC, fomfom commented on lib/giocci/hello.ex
> +end
すみません、消してmix formatしたものをpushしました。

2024-12-16 06:50 UTC, s-hosoai requested changes

2024-12-16 06:50 UTC, s-hosoai commented on lib/giocci.ex
> +  def start_link_session_rc() do
慣例的にGenServerの実装はstart_linkで初期化なので、ここも素直にstart_linkでいいかと思います。setup_clientで再度ラップしてますが何か意図はありますか？

2024-12-16 08:10 UTC, fomfom commented on lib/giocci.ex
> +  def start_link_session_rc() do
すみません、実装で要らなくなったものを消した際、こうなっていることに気づきませんでした。修正します

2024-12-16 08:56 UTC, s-hosoai approved these changes

2024-12-23 01:34 UTC, closed without merging